config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats(<%= @flats.count %>)</h1>
    <div class="container d-flex">
      <% @flats.each do |flat| %>
          <div lass="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="row">
                <i class="fas fa-user-friends pr-3 pl-3"> <%= flat.number_of_guests %></i>
                <i class="fas fa-euro-sign"><%= flat.price_per_night %></i>
              </div>
            </div>
          </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light justify-content-between">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <div class="navbar-nav">
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>